- name: apt-get update
  shell: apt-get update

- name: Install packages to allow apt to use a repository over HTTPS
  shell: apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common

- name: Add Docker’s official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Verify
  shell: apt-key fingerprint 0EBFCD88

- name: Additional install
  shell: apt install apt-transport-https ca-certificates curl software-properties-common

- name: Additional key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Additional responsity
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic test"

- name: apt-get update
  shell: apt-get update

- name: final install
  shell: apt-get install -y docker-ce docker-ce-cli containerd.io

- name: install docker-compose
  shell: pip install docker-compose
